name = 'hayfrp-auto-sign'
main = 'src/index.ts'
compatibility_date = "2025-08-22"

[observability]
enabled = true
logs = { enabled = true }

[placement]
mode = "smart"

[triggers]
# 默认每天 1:14 (CST, UTC -> 17:14) 执行一次, 可自行修改 (注意是 UTC 时间!!!)
crons = ["14 17 * * *"]

[vars]
# HayFrp API 地址
API_URL = "https://api.hayfrp.com"
# 手动执行的访问密钥 (路径)
ACCESS_KEY = "disabled"